### PR TITLE
PHP 8.1 Compatibility

### PR DESCRIPTION
**Pull request by SychO9**
Hello! great package!

As f PHP 8.1 `readonly` is a unique keyword and therefore a class/interface/trait cannot be named as such.

This PR supercedes (https://github.com/axypro/sourcemap/pull/7).

### CODE REVIEW

**Comment by vasa-c** [comment]
@SychO9 thanx

**Comment by leowhite90** [comment]
I'm trying to install this commit with composer update after 0.1.5 but getting this error
Your requirements could not be resolved to an installable set of packages.

    - Root composer.json requires axy/sourcemap dev-master#aaea981 -> satisfiable by axy/sourcemap[dev-master].
    - axy/sourcemap dev-master requires axy/errors ^3.0 -> found axy/errors[dev-master, dev-php5, 0.0.1, ..., 0.0.5, 1.0.0, ..., 1.0.5, 2.0.0, 2.1.0] but it does not match the constraint.

**Comment by vasa-c** [comment]
@leowhite90 will fix it soon

**Comment by vasa-c** [comment]
@leowhite90 axy\errors 3.0.0 and axy\sourcemap 1.0.0, check, please

**Pull request merged**
